---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: dotnettest-deployment
spec:
  template:
    metadata: 
      labels:
        app: dotnetcorepractice
    spec: 
      containers:
        - name: dotnetcorepractice
          image: dotnetcorepractice:latest
          ports: 
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: dotnettest-service
  labels:
    app: dotnetcorepractice
spec:
  type: NodePort
  ports: 
    - port: 5001
      nodePort: 30001
  selector: 
    app: dotnetcorepractice